esphome:
  name: ${devicename}
  project:
    name: "athom.smart-plug-v2"
    version: "1.1"

esp8266:
  board: esp8285
  restore_from_flash: true

# Turn on the web server
web_server:

preferences:
  flash_write_interval: 10min

dashboard_import:
  package_import_url: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

globals:
  - id: total_energy
    type: float
    restore_value: yes
    initial_value: '0.0'

binary_sensor:
  - platform: gpio
    pin:
      number: 5
      mode: INPUT_PULLUP
      inverted: true
    name: "${human_devicename} Power Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.toggle: relay
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

sensor:
  - platform: cse7766
    update_interval: 10s
    current:
      name: "${human_devicename} Current"
      filters:
        - lambda: if (x < 0.060) return 0.0; else return x;   #For the chip will report less than 3w power when no load is connected


    voltage:
      name: "${human_devicename} Voltage"
    power:
      name: "${human_devicename} Power"
      id: power_sensor
      filters:
        - lambda: if (x < 3.0) return 0.0; else return x;    #For the chip will report less than 3w power when no load is connected


    energy:
      name: "${human_devicename} Energy"
      id: energy
      unit_of_measurement: kWh
      filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
      on_value:
        then:
          - lambda: |-
              static float previous_energy_value = 0.0;
              float current_energy_value = id(energy).state;
              id(total_energy) += current_energy_value - previous_energy_value;
              previous_energy_value = current_energy_value;

  - platform: template
    name: "${human_devicename} Total Energy"
    unit_of_measurement: kWh
    device_class: "energy"
    state_class: "total_increasing"
    icon: "mdi:lightning-bolt"
    accuracy_decimals: 3
    lambda: |-
      return id(total_energy);
    update_interval: 10s

  - platform: total_daily_energy
    name: "${human_devicename} Total Daily Energy"
    restore: true
    power_id: power_sensor
    unit_of_measurement: kWh
    accuracy_decimals: 3
    filters:
      - multiply: 0.001


button:
  - platform: factory_reset
    name: "${human_devicename} Restart with Factory Default Settings"
    id: Reset

switch:
  - platform: gpio
    name: "${human_devicename} Relay"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_ON

light:
  - platform: status_led
    name: "${human_devicename} Status LED"
    id: blue_led
    disabled_by_default: true
    pin:
      inverted: true
      number: GPIO13
