esphome:
  name: ${devicename}
  platform: esp8266
  board: d1_mini

# Turn on the web server
web_server:

# Turn on the prometheus /metrics endpoint
prometheus:

preferences:
  flash_write_interval: 10min

logger:
