esphome:
  name: ${devicename}
  platform: ESP32
  board: esp32dev

# Turn on the web server
web_server:

# Turn on the prometheus /metrics endpoint
prometheus:

preferences:
  flash_write_interval: 10min

logger:

packages:
  mqtt: !include  ../mqtt.yaml
