esphome:
  name: ${devicename}

rp2040:
  board: rpipicow
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git#5e87ae34ca025274df25b3303e9e9cb6c120123c

preferences:
  flash_write_interval: 10min

logger:
