######################################3
#
# MQTT Events
#

# Laundry room
- alias: "MQTT - Laundry Room Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.laundry_room_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/laundry_room/motion"
      payload_template: "{{ states.binary_sensor.laundry_room_motion.state }}"

- alias: "MQTT - Laundry Room Temperature"
  trigger:
    platform: state
    entity_id: "sensor.laundry_room_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/laundry_room/temperature"
      payload_template: "{{ states.sensor.laundry_room_temperature.state }}"


# Half Bathroom
- alias: "MQTT - Half Bathroom Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.half_bathroom_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/half_bathroom/motion"
      payload_template: "{{ states.binary_sensor.half_bathroom_motion.state }}"

- alias: "MQTT - Half Bathroom Temperature"
  trigger:
    platform: state
    entity_id: "sensor.half_bathroom_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/half_bathroom/temperature"
      payload_template: "{{ states.sensor.half_bathroom_temperature.state }}"

# Hallway Bathroom
- alias: "MQTT - Hallway Bathroom Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.hallway_bathroom_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/hallway_bathroom/motion"
      payload_template: "{{ states.binary_sensor.hallway_bathroom_motion.state }}"

- alias: "MQTT - Hallway Bathroom Temperature"
  trigger:
    platform: state
    entity_id: "sensor.hallway_bathroom_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/hallway_bathroom/temperature"
      payload_template: "{{ states.sensor.hallway_bathroom_temperature.state }}"

# Office
# Kitchen
- alias: "MQTT - Kitchen Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.kitchen_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/kitchen/motion"
      payload_template: "{{ states.binary_sensor.kitchen_motion.state }}"

- alias: "MQTT - Kitchen Temperature"
  trigger:
    platform: state
    entity_id: "sensor.kitchen_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/kitchen/temperature"
      payload_template: "{{ states.sensor.kitchen_temperature.state }}"

## Things!

# Bedroom Fan
- alias: "MQTT - Bedroom Fan State"
  trigger:
    platform: state
    entity_id: "switch.bedroom_fan"
  action:
    service: mqtt.publish
    data:
      topic: "thing/bedroom/fan/state"
      payload_template: "{{ states.switch.bedroom_fan.state }}"

- alias: "MQTT - Bedroom Fan Power"
  trigger:
    platform: state
    entity_id: "sensor.bedroom_fan_power"
  action:
    service: mqtt.publish
    data:
      topic: "thing/bedroom/fan/power"
      payload_template: "{{ states.sensor.bedroom_fan_power.state }}"

- alias: "MQTT - Everyone Home"
  trigger:
    platform: state
    entity_id: "group.all_furries"
  action:
    service: mqtt.publish
    data:
      topic: "people/furries/home"
      payload_template: "{{ states.group.all_furries.state }}"





