######################################3
#
# MQTT Events
#

# Laundry room
- alias: "MQTT - Laundry Room Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.laundry_room_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/laundry_room/motion"
      payload_template: "{{ states.binary_sensor.laundry_room_motion.state }}"

- alias: "MQTT - Laundry Room Temperature"
  trigger:
    platform: state
    entity_id: "sensor.laundry_room_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/laundry_room/temperature"
      payload_template: "{{ states.sensor.laundry_room_temperature.state }}"

- alias: "MQTT - Laundry Room Room Humidity"
  trigger:
    platform: state
    entity_id: "sensor.laundry_room_relative_humidity"
  action:
    service: mqtt.publish
    data:
      topic: "home/laundry_room/humidity"
      payload_template: "{{ states.sensor.laundry_room_relative_humidity.state }}"

# Bedroom
- alias: "MQTT - Bedroom Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.bedroom_motion_sensor_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/bedroom/motion"
      payload_template: "{{ states.binary_sensor.bedroom_motion_sensor_motion.state }}"

- alias: "MQTT - Bedroom Temperature"
  trigger:
    platform: state
    entity_id: "sensor.bedroom_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/bedroom/temperature"
      payload_template: "{{ states.sensor.bedroom_temperature.state }}"

# Half Bathroom
- alias: "MQTT - Half Bathroom Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.half_bathroom_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/half_bathroom/motion"
      payload_template: "{{ states.binary_sensor.half_bathroom_motion.state }}"

- alias: "MQTT - Half Bathroom Temperature"
  trigger:
    platform: state
    entity_id: "sensor.half_bathroom_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/half_bathroom/temperature"
      payload_template: "{{ states.sensor.half_bathroom_temperature.state }}"

- alias: "MQTT - Half Bathroom Room Humidity"
  trigger:
    platform: state
    entity_id: "sensor.half_bathroom_relative_humidity"
  action:
    service: mqtt.publish
    data:
      topic: "home/half_bathroom/humidity"
      payload_template: "{{ states.sensor.half_bathroom_relative_humidity.state }}"

# Hallway Bathroom
- alias: "MQTT - Hallway Bathroom Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.hallway_bathroom_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/hallway_bathroom/motion"
      payload_template: "{{ states.binary_sensor.hallway_bathroom_motion.state }}"

- alias: "MQTT - Hallway Bathroom Temperature"
  trigger:
    platform: state
    entity_id: "sensor.hallway_bathroom_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/hallway_bathroom/temperature"
      payload_template: "{{ states.sensor.hallway_bathroom_temperature.state }}"

- alias: "MQTT - Hallway Bathroom Room Humidity"
  trigger:
    platform: state
    entity_id: "sensor.hallway_bathroom_relative_humidity"
  action:
    service: mqtt.publish
    data:
      topic: "home/hallway_bathroom/humidity"
      payload_template: "{{ states.sensor.hallway_bathroom_relative_humidity.state }}"

# Office
- alias: "MQTT - Office Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.office_motion_sensor_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/office/motion"
      payload_template: "{{ states.binary_sensor.office_motion_sensor_motion.state }}"

- alias: "MQTT - Office Temperature"
  trigger:
    platform: state
    entity_id: "sensor.office_motion_sensor_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/office/temperature"
      payload_template: "{{ states.sensor.office_motion_sensor_temperature.state }}"

# Kitchen
- alias: "MQTT - Kitchen Motion"
  trigger:
    platform: state
    entity_id: "binary_sensor.kitchen_motion"
  action:
    service: mqtt.publish
    data:
      topic: "home/kitchen/motion"
      payload_template: "{{ states.binary_sensor.kitchen_motion.state }}"

- alias: "MQTT - Kitchen Temperature"
  trigger:
    platform: state
    entity_id: "sensor.kitchen_temperature"
  action:
    service: mqtt.publish
    data:
      topic: "home/kitchen/temperature"
      payload_template: "{{ states.sensor.kitchen_temperature.state }}"

- alias: "MQTT - Kitchen Humidity"
  trigger:
    platform: state
    entity_id: "sensor.kitchen_relative_humidity"
  action:
    service: mqtt.publish
    data:
      topic: "home/kitchen/humidity"
      payload_template: "{{ states.sensor.kitchen_relative_humidity.state }}"

# Outside
- alias: "MQTT - Outside Humidity"
  trigger:
    platform: state
    entity_id: "sensor.outside_humidity"
  action:
    service: mqtt.publish
    data:
      topic: "home/outside/humidity"
      payload_template: "{{ states.sensor.outside_humidity.state }}"

- alias: "MQTT - Outside Wind Bearing"
  trigger:
    platform: state
    entity_id: "sensor.wind_bearing"
  action:
    service: mqtt.publish
    data:
      topic: "home/outside/wind_bearing"
      payload_template: "{{ states.sensor.wind_bearing.state }}"

- alias: "MQTT - Outside Wind Direction"
  trigger:
    platform: state
    entity_id: "sensor.wind_direction"
  action:
    service: mqtt.publish
    data:
      topic: "home/outside/wind_direction"
      payload_template: "{{ states.sensor.wind_direction.state }}"

- alias: "MQTT - Outside Conditions"
  trigger:
    platform: state
    entity_id: "weather.april_s_nest"
  action:
    service: mqtt.publish
    data:
      topic: "home/outside/conditions"
      payload_template: "{{ states.weather.april_s_nest.state }}"

- alias: "MQTT - Outside Sun"
  trigger:
    platform: state
    entity_id: "sun.sun"
  action:
    service: mqtt.publish
    data:
      topic: "home/outside/sun"
      payload_template: "{{ states.sun.sun.state }}"

- alias: "MQTT - Outside Air Quailty"
  trigger:
    platform: state
    entity_id: "sensor.airnow_aqi"
  action:
    service: mqtt.publish
    data:
      topic: "home/outside/air_quality"
      payload_template: "{{ states.sensor.airnow_aqi.state }}"

## Things!

# Living Room Heater
- alias: "MQTT - Living Room Heater State"
  trigger:
    platform: state
    entity_id: "switch.living_room_heater"
  action:
    service: mqtt.publish
    data:
      topic: "thing/living_room/heater/state"
      payload_template: "{{ states.switch.living_room_heater.state }}"

- alias: "MQTT - Living Room Heater Power"
  trigger:
    platform: state
    entity_id: "sensor.living_room_heater_power"
  action:
    service: mqtt.publish
    data:
      topic: "thing/living_room/heater/power"
      payload_template: "{{ states.sensor.living_room_heater_power.state }}"

# Bedroom Fan
- alias: "MQTT - Bedroom Fan State"
  trigger:
    platform: state
    entity_id: "switch.bedroom_fan"
  action:
    service: mqtt.publish
    data:
      topic: "thing/bedroom/fan/state"
      payload_template: "{{ states.switch.bedroom_fan.state }}"

- alias: "MQTT - Bedroom Fan Power"
  trigger:
    platform: state
    entity_id: "sensor.bedroom_fan_power"
  action:
    service: mqtt.publish
    data:
      topic: "thing/bedroom/fan/power"
      payload_template: "{{ states.sensor.bedroom_fan_power.state }}"

- alias: "MQTT - Everyone Home"
  trigger:
    platform: state
    entity_id: "group.all_furries"
  action:
    service: mqtt.publish
    data:
      topic: "people/furries/home"
      payload_template: "{{ states.group.all_furries.state }}"

- alias: "MQTT - Living Room TV"
  trigger:
    platform: state
    entity_id: "media_player.living_room_tv"
  action:
    service: mqtt.publish
    data:
      topic: "thing/living_room/tv/state"
      payload_template: "{{ states.media_player.living_room_tv.state }}"

- alias: "MQTT - Work Computer Camera"
  trigger:
    platform: state
    entity_id: "binary_sensor.april_s_work_mac_mini_camera_in_use"
  action:
    service: mqtt.publish
    data:
      topic: "thing/office/computer_camera/state"
      payload_template: "{{ states.binary_sensor.april_s_work_mac_mini_camera_in_usestate }}"

- alias: "MQTT - Work Computer Microphone"
  trigger:
    platform: state
    entity_id: "binary_sensor.april_s_work_mac_mini_microphone_in_use"
  action:
    service: mqtt.publish
    data:
      topic: "thing/office/computer_microphone/state"
      payload_template: "{{ states.binary_sensor.april_s_work_mac_mini_microphone_in_use.state }}"




