#
# The Zooz 4-in-1 sensors use the "burglar" type to report motion, so let's
# map that to what HA expects instead.
#
# See https://www.home-assistant.io/docs/z-wave/entities#burglar-entity
#
- platform: template
  sensors:
    carport_motion:
      friendly_name: "Carport Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.carport_burglar', '8') }}"
- platform: template
  sensors:
    guest_room_motion:
      friendly_name: "Guest Room Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.guest_room_burglar', '8') }}"

- platform: template
  sensors:
    half_bathroom_motion:
      friendly_name: "Half Bathroom Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.half_bathroom_burglar', '8') }}"

- platform: template
  sensors:
    hallway_bathroom_motion:
      friendly_name: "Hallway Bathroom Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.hallway_bathroom_burglar', '8') }}"

- platform: template
  sensors:
    kitchen_motion:
      friendly_name: "Kitchen Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.kitchen_burglar', '8') }}"

- platform: template
  sensors:
    laundry_room_motion:
      friendly_name: "Laundry Room Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.laundry_room_burglar', '8') }}"

# Inovelli LZW60
- platform: template
  sensors:
    mud_room_motion:
      friendly_name: "Mud Room Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.mud_room_burglar', '8') }}"

# This one is an Aeotec MutliSensor 6
- platform: template
  sensors:
    workshop_motion:
      friendly_name: "Workshop Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.workshop_burglar', '8') }}"

#
# Smoke and CO alarms
#

# Bunny's Room
- platform: template
  sensors:
    bunnys_room_smoke:
      friendly_name: "Bunny's Room Smoke"
      unique_id: "a7fa1857-2f79-41f1-a750-70d5ca52832e"
      device_class: smoke
      value_template: "{{ is_state('sensor.bunnys_room_smoke_detector_smoke', '2') }}"
- platform: template
  sensors:
    bunnys_room_carbon_monoxide:
      friendly_name: "Bunny's Room Carbon Monoxide"
      unique_id: "a6a57840-ab4a-492c-bcb6-01390f079101"
      device_class: gas
      value_template: "{{ is_state('sensor.bunnys_room_smoke_detector_carbon_monoxide', '2') }}"

# Family Room
- platform: template
  sensors:
    family_room_smoke:
      friendly_name: "Family Room Smoke"
      unique_id: "9b5cba89-81ad-4d13-a03b-e0b427eaaaac"
      device_class: smoke
      value_template: "{{ is_state('sensor.family_room_smoke_detector_smoke', '2') }}"
- platform: template
  sensors:
    family_room_carbon_monoxide:
      friendly_name: "Family Room Carbon Monoxide"
      unique_id: "78967f4b-5390-4e6a-b764-28ec03e2dc3f"
      device_class: gas
      value_template: "{{ is_state('sensor.family_room_smoke_detector_carbon_monoxide', '2') }}"

# Guest Room
- platform: template
  sensors:
    guest_room_smoke:
      friendly_name: "Guest Room Smoke"
      unique_id: "c142accc-aa1e-4dd3-9720-03ab269c95f3"
      device_class: smoke
      value_template: "{{ is_state('sensor.guest_room_smoke_alarm_smoke', '2') }}"
- platform: template
  sensors:
    guest_room_carbon_monoxide:
      friendly_name: "Guest Room Carbon Monoxide"
      unique_id: "533e7932-a0b2-440b-8380-842c56fe8617"
      device_class: gas
      value_template: "{{ is_state('sensor.guest_room_smoke_alarm_carbon_monoxide', '2') }}"

# Kitchen
- platform: template
  sensors:
    kitchen_smoke:
      friendly_name: "Kitchen Smoke"
      unique_id: "34db2aff-49bb-4a7f-bc7a-7b5a473bfe0d"
      device_class: smoke
      value_template: "{{ is_state('sensor.kitchen_smoke_detector_smoke', '2') }}"
- platform: template
  sensors:
    kitchen_carbon_monoxide:
      friendly_name: "Kitchen Carbon Monoxide"
      unique_id: "1bd9c920-b042-4319-a35f-879fb3071abd"
      device_class: gas
      value_template: "{{ is_state('sensor.kitchen_smoke_detector_carbon_monoxide', '2') }}"
