

#
# Smoke and CO alarms
#

# Bunny's Room
- platform: template
  sensors:
    bunnys_room_smoke:
      friendly_name: "Bunny's Room Smoke"
      unique_id: "a7fa1857-2f79-41f1-a750-70d5ca52832e"
      device_class: smoke
      value_template: "{{ is_state('sensor.bunnys_room_smoke_detector_smoke', '2') }}"
- platform: template
  sensors:
    bunnys_room_carbon_monoxide:
      friendly_name: "Bunny's Room Carbon Monoxide"
      unique_id: "a6a57840-ab4a-492c-bcb6-01390f079101"
      device_class: gas
      value_template: "{{ is_state('sensor.bunnys_room_smoke_detector_carbon_monoxide', '2') }}"

# Family Room
- platform: template
  sensors:
    family_room_smoke:
      friendly_name: "Family Room Smoke"
      unique_id: "9b5cba89-81ad-4d13-a03b-e0b427eaaaac"
      device_class: smoke
      value_template: "{{ is_state('sensor.family_room_smoke_detector_smoke', '2') }}"
- platform: template
  sensors:
    family_room_carbon_monoxide:
      friendly_name: "Family Room Carbon Monoxide"
      unique_id: "78967f4b-5390-4e6a-b764-28ec03e2dc3f"
      device_class: gas
      value_template: "{{ is_state('sensor.family_room_smoke_detector_carbon_monoxide', '2') }}"

# Guest Room
- platform: template
  sensors:
    guest_room_smoke:
      friendly_name: "Guest Room Smoke"
      unique_id: "c142accc-aa1e-4dd3-9720-03ab269c95f3"
      device_class: smoke
      value_template: "{{ is_state('sensor.guest_room_smoke_alarm_smoke', '2') }}"
- platform: template
  sensors:
    guest_room_carbon_monoxide:
      friendly_name: "Guest Room Carbon Monoxide"
      unique_id: "533e7932-a0b2-440b-8380-842c56fe8617"
      device_class: gas
      value_template: "{{ is_state('sensor.guest_room_smoke_alarm_carbon_monoxide', '2') }}"

# Kitchen
- platform: template
  sensors:
    kitchen_smoke:
      friendly_name: "Kitchen Smoke"
      unique_id: "34db2aff-49bb-4a7f-bc7a-7b5a473bfe0d"
      device_class: smoke
      value_template: "{{ is_state('sensor.kitchen_smoke_detector_smoke', '2') }}"
- platform: template
  sensors:
    kitchen_carbon_monoxide:
      friendly_name: "Kitchen Carbon Monoxide"
      unique_id: "1bd9c920-b042-4319-a35f-879fb3071abd"
      device_class: gas
      value_template: "{{ is_state('sensor.kitchen_smoke_detector_carbon_monoxide', '2') }}"

# Mud Room
- platform: template
  sensors:
    mud_room_smoke:
      friendly_name: "Mud Room Smoke"
      unique_id: "71dc046e-08de-4b1a-8bdb-a8a0697f82b8"
      device_class: smoke
      value_template: "{{ is_state('sensor.mud_room_smoke_detector_smoke', '2') }}"
- platform: template
  sensors:
    mud_room_carbon_monoxide:
      friendly_name: "Mud Room Carbon Monoxide"
      unique_id: "1ec45101-f16d-4b74-b41a-29725f9a0b4f"
      device_class: gas
      value_template: "{{ is_state('sensor.mud_room_smoke_detector_carbon_monoxide', '2') }}"

# Workshop
- platform: template
  sensors:
    workshop_smoke:
      friendly_name: "Workshop Smoke"
      unique_id: "eb960bf7-dbde-42c0-b891-1f573e7c58e3"
      device_class: smoke
      value_template: "{{ is_state('sensor.workshop_smoke_detector_smoke', '2') }}"
- platform: template
  sensors:
    workshop_carbon_monoxide:
      friendly_name: "Workshop Carbon Monoxide"
      unique_id: "ef32759d-d3a9-4401-ae2c-2ea2d62c0f6b"
      device_class: gas
      value_template: "{{ is_state('sensor.workshop_smoke_detector_carbon_monoxide', '2') }}"
