#
# Let's be goofy and allow Siri to turn off the clock :)
#

- platform: template
  lights:
    family_room_clock:
      friendly_name: "Family Room Clock"
      value_template: "{{ states('input_boolean.creatures_clocky_yellow_display_on') }}"
      turn_on:
        - service: input_boolean.turn_on
          data:
            entity_id:
              - input_boolean.creatures_clocky_yellow_display_on
      turn_off:
        - service: input_boolean.turn_off
          data:
            entity_id:
              - input_boolean.creatures_clocky_yellow_display_on

#
# This templates define lights that wrap the groups, mostly
# so that I can expose the groups to HomeKit
#

- platform: template
  lights:
    family_room_lights:
      friendly_name: "Family Room Lights"
      value_template: "{{ states('group.family_room_lights') }}"
      turn_on:
        - service: homeassistant.turn_on
          data:
            entity_id:
              - group.family_room_lights
      turn_off:
        - service: homeassistant.turn_off
          data:
            entity_id:
              - group.family_room_lights

- platform: template
  lights:
    kitchen_lights:
      friendly_name: "Kitchen Lights"
      value_template: "{{ states('group.kitchen_lights') }}"
      turn_on:
        - service: homeassistant.turn_on
          data:
            entity_id:
              - group.kitchen_lights
      turn_off:
        - service: homeassistant.turn_off
          data:
            entity_id:
              - group.kitchen_lights

- platform: template
  lights:
    office_lights:
      friendly_name: "Office Lights"
      value_template: "{{ states('group.office_lights') }}"
      turn_on:
        - service: homeassistant.turn_on
          data:
            entity_id:
              - group.office_lights
      turn_off:
        - service: homeassistant.turn_off
          data:
            entity_id:
              - group.office_lights

- platform: template
  lights:
    workshop_lights:
      friendly_name: "Workshop Lights"
      value_template: "{{ states('group.workshop_lights') }}"
      turn_on:
        - service: homeassistant.turn_on
          data:
            entity_id:
              - group.workshop_lights
      turn_off:
        - service: homeassistant.turn_off
          data:
            entity_id:
              - group.workshop_lights

- platform: template
  lights:
    bunnys_room_lights:
      friendly_name: "Bunny's Room Lights"
      value_template: "{{ states('group.bunnys_room_lights') }}"
      turn_on:
        - service: homeassistant.turn_on
          data:
            entity_id:
              - group.bunnys_room_lights
      turn_off:
        - service: homeassistant.turn_off
          data:
            entity_id:
              - group.bunnys_room_lights

- platform: template
  lights:
    guest_room_lights:
      friendly_name: "Guest Room Lights"
      value_template: "{{ states('group.guest_room_lights') }}"
      turn_on:
        - service: homeassistant.turn_on
          data:
            entity_id:
              - group.guest_room_lights
      turn_off:
        - service: homeassistant.turn_off
          data:
            entity_id:
              - group.guest_room_lights

- platform: template
  lights:
    hallway_lights:
      friendly_name: "Hallway Lights"
      value_template: "{{ states('group.hallway_lights') }}"
      turn_on:
        - service: homeassistant.turn_on
          data:
            entity_id:
              - group.hallway_lights
      turn_off:
        - service: homeassistant.turn_off
          data:
            entity_id:
              - group.hallway_lights

- platform: template
  lights:
    hallway_bathroom_lights:
      friendly_name: "Hallway Bathroom Lights"
      value_template: "{{ states('group.hallway_bathroom_lights') }}"
      turn_on:
        - service: homeassistant.turn_on
          data:
            entity_id:
              - group.hallway_bathroom_lights
      turn_off:
        - service: homeassistant.turn_off
          data:
            entity_id:
              - group.hallway_bathroom_lights

- platform: template
  lights:
    half_bathroom_lights:
      friendly_name: "Half Bathroom Lights"
      value_template: "{{ states('group.half_bathroom_lights') }}"
      turn_on:
        - service: homeassistant.turn_on
          data:
            entity_id:
              - group.half_bathroom_lights
      turn_off:
        - service: homeassistant.turn_off
          data:
            entity_id:
              - group.half_bathroom_lights

- platform: template
  lights:
    laundry_room_lights:
      friendly_name: "Laundry Room Lights"
      value_template: "{{ states('group.laundry_room_lights') }}"
      turn_on:
        - service: homeassistant.turn_on
          data:
            entity_id:
              - group.laundry_room_lights
      turn_off:
        - service: homeassistant.turn_off
          data:
            entity_id:
              - group.laundry_room_lights
