#
# Manually defined sensors
#

### MQTT

- platform: mqtt
  name: "Second Life Concurrency"
  state_topic: "external/secondlife/concurrency"
  unit_of_measurement: "resis"
  icon: mdi:account-group

# Weather

# This data comes from dutch, which is reading a sensor on the roof of the
# house and publishing the data via MQTT. ðŸ¡
- platform: mqtt
  name: "Outside Temperature"
  state_topic: "weather/Acurite-5n1/temperature_F"
  unit_of_measurement: "Â°F"
  device_class: temperature
  icon: mdi:thermometer

- platform: mqtt
  name: "Outside Humidity"
  state_topic: "weather/Acurite-5n1/humidity"
  unit_of_measurement: "%"
  device_class: humidity
  icon: mdi:water-percent

- platform: mqtt
  name: "Wind Bearing"
  state_topic: "weather/Acurite-5n1/wind_dir_deg"
  unit_of_measurement: "deg"
  icon: mdi:compass

- platform: mqtt
  name: "Wind Speed (Avg)"
  state_topic: "weather/Acurite-5n1/wind_avg_mi_h"
  unit_of_measurement: "mph"
  icon: mdi:weather-windy

- platform: mqtt
  name: "Rain Amount"
  state_topic: "weather/Acurite-5n1/rain_in"
  unit_of_measurement: "inches"
  icon: mdi:weather-rainy
### End MQTT

- platform: template
  sensors:
    wind_direction:
      value_template: >
        {% set direction = ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW','N'] %}
        {% set degree = states('sensor.wind_bearing')|float %}
        {{ direction[((degree+11.25)/22.5)|int] }}
