#
# Manually defined sensors
#

### MQTT

- platform: mqtt
  name: "Second Life Concurrency"
  state_topic: "external/secondlife/concurrency"
  unit_of_measurement: "resis"
  icon: mdi:account-group

# Weather

# This data comes from dutch, which is reading a sensor on the roof of the
# house and publishing the data via MQTT. ðŸ¡
- platform: mqtt
  name: "Outside Temperature"
  state_topic: "weather/Acurite-5n1/temperature_F"
  unit_of_measurement: "Â°F"
  device_class: temperature
  icon: mdi:thermometer

- platform: mqtt
  name: "Outside Humidity"
  state_topic: "weather/Acurite-5n1/humidity"
  unit_of_measurement: "%"
  device_class: humidity
  icon: mdi:water-percent

- platform: mqtt
  name: "Wind Bearing"
  state_topic: "weather/Acurite-5n1/wind_dir_deg"
  unit_of_measurement: "deg"
  icon: mdi:compass

- platform: mqtt
  name: "Wind Speed (Avg)"
  state_topic: "weather/Acurite-5n1/wind_avg_mi_h"
  unit_of_measurement: "mph"
  icon: mdi:weather-windy

- platform: mqtt
  name: "Rain Amount"
  state_topic: "weather/Acurite-5n1/rain_in"
  unit_of_measurement: "in"
  icon: mdi:weather-rainy
### End MQTT

# This allows me to see how much rain has come in today, rather than
# over the lifetime of the senor
- platform: mqtt
  state_topic: "internal/rain_in_prior"
  name: "rain_in_prior"
  unit_of_measurement: "in"
- platform: template
  sensors:
    rain_today:
      value_template: >
        {%- if not (is_state("sensor.rain_amount","unknown") or is_state("sensor.rain_in_prior","unknown") )-%}
        {{ ((states.sensor.rain_amount.state | float) - (states.sensor.rain_in_prior.state | float)) | max (0) | round(2) }}
        {%- endif -%}
      friendly_name: "Rain Today"
      unit_of_measurement: "in"

# Show the wind in human units
- platform: template
  sensors:
    wind_direction:
      value_template: >
        {% set direction = ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW','N'] %}
        {% set degree = states('sensor.wind_bearing')|float %}
        {{ direction[((degree+11.25)/22.5)|int] }}
      friendly_name: "Wind Direction"

# On devices that have a "previous reading" for energy, show the difference
- platform: template
  sensors:
    bedroom_fan_current_energy:
      value_template: >-
        {% set current = states('sensor.bedroom_fan_energy') | float %}
        {% set previous = states('sensor.bedroom_fan_energy_previous_reading') | float %}
        {{ current - previous }}
      friendly_name: "Bedroom Fan Current Energy"
      unit_of_measurement: "kWh"

#
# Smoke and CO alarms
#
- platform: template
  sensors:
    guest_room_fire_alarm_status:
      friendly_name: "Guest Room Fire Alarm Status"
      unique_id: "7c6635be-2a59-4301-8a75-0cb9c7493104"
      value_template: >-
        {% if is_state('sensor.guest_room_smoke_alarm_smoke', '3') %}
          Testing
        {% elif is_state('sensor.guest_room_smoke_alarm_smoke', '2') %}
          Smoke
        {% elif is_state('sensor.guest_room_smoke_alarm_carbon_monoxide', '2') %}
          CO
        {% elif is_state('sensor.guest_room_smoke_alarm_smoke', '6') or is_state('sensor.guest_room_smoke_alarm_carbon_monoxide', '6') %}
          Silenced
        {% elif is_state('sensor.guest_room_smoke_alarm_carbon_monoxide', '5') %}
          CO_EOL
        {% else %}
          Clear
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.guest_room_smoke_alarm_smoke', '3') %}
          mdi:cloud-alert
        {% elif is_state('sensor.guest_room_smoke_alarm_smoke', '2') %}
          mdi:fire
        {% elif is_state('sensor.guest_room_smoke_alarm_carbon_monoxide', '2') %}
          mdi:cloud-alert
        {% elif is_state('sensor.guest_room_smoke_alarm_smoke', '6') or is_state('sensor.guest_room_smoke_alarm_carbon_monoxide', '6') %}
          mdi:volume-mute
        {% elif is_state('sensor.guest_room_smoke_alarm_carbon_monoxide', '5') %}
          mdi:cloud-alert
        {% else %}
          mdi:smoke-detector
        {% endif %}
- platform: template
  sensors:
    guest_room_fire_alarm_health:
      friendly_name: "Guest Room Fire Alarm Health"
      unique_id: "c079bc5d-cb90-496e-a993-fed3c55730c3"
      value_template: >-
        {% if is_state('sensor.guest_room_smoke_alarm_system', '5') %}
          Healthy
        {% elif is_state('sensor.guest_room_smoke_alarm_system', '1') %}
          Malfunction Detected
        {% elif is_state('sensor.guest_room_smoke_alarm_system', '0')  %}
          Malfunction Clear
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.guest_room_smoke_alarm_system', '5') %}
          mdi:check-decagram
        {% elif is_state('sensor.guest_room_smoke_alarm_system', '1') %}
          mdi:alert
        {% elif is_state('sensor.guest_room_smoke_alarm_system', '0')  %}
          mdi:alert-circle-check
        {% else %}
          mdi:help-rhombus
        {% endif %}
