
- platform: template
  sensors:
    bunnys_room_smoke_detector_status:
      friendly_name: "Bunny's Room Smoke Detector Status"
      unique_id: "e102dd7c-73f7-4768-9895-72e7dc46b158"
      value_template: >-
        {% if is_state('sensor.bunnys_room_smoke_detector_smoke', '3') %}
          Testing
        {% elif is_state('sensor.bunnys_room_smoke_detector_smoke', '2') %}
          Smoke
        {% elif is_state('sensor.bunnys_room_smoke_detector_carbon_monoxide', '2') %}
          CO
        {% elif is_state('sensor.bunnys_room_smoke_detector_smoke', '6') or is_state('sensor.bunnys_room_smoke_detector_carbon_monoxide', '6') %}
          Silenced
        {% elif is_state('sensor.bunnys_room_smoke_detector_carbon_monoxide', '5') %}
          CO_EOL
        {% else %}
          Clear
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.bunnys_room_smoke_detector_smoke', '3') %}
          mdi:cloud-alert
        {% elif is_state('sensor.bunnys_room_smoke_detector_smoke', '2') %}
          mdi:fire
        {% elif is_state('sensor.bunnys_room_smoke_detector_carbon_monoxide', '2') %}
          mdi:cloud-alert
        {% elif is_state('sensor.bunnys_room_smoke_detector_smoke', '6') or is_state('sensor.bunnys_room_smoke_detector_carbon_monoxide', '6') %}
          mdi:volume-mute
        {% elif is_state('sensor.bunnys_room_smoke_detector_carbon_monoxide', '5') %}
          mdi:cloud-alert
        {% else %}
          mdi:smoke-detector
        {% endif %}
- platform: template
  sensors:
    bunnys_room_smoke_detector_health:
      friendly_name: "Bunny's Room Smoke Detector Health"
      unique_id: "10491fa7-3001-4e75-9dcb-acc39f7e5bab"
      value_template: >-
        {% if is_state('sensor.bunnys_room_smoke_detector_system', '5') %}
          Healthy
        {% elif is_state('sensor.bunnys_room_smoke_detector_system', '1') %}
          Malfunction Detected
        {% elif is_state('sensor.bunnys_room_smoke_detector_system', '0')  %}
          Malfunction Clear
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.bunnys_room_smoke_detector_system', '5') %}
          mdi:check-decagram
        {% elif is_state('sensor.bunnys_room_smoke_detector_system', '1') %}
          mdi:alert
        {% elif is_state('sensor.bunnys_room_smoke_detector_system', '0')  %}
          mdi:alert-circle-check
        {% else %}
          mdi:help-rhombus
        {% endif %}
