- platform: template
  sensors:
    mud_room_fire_alarm_status:
      friendly_name: "Mud Room Fire Alarm Status"
      unique_id: "4300e2f9-be59-4df7-b1e8-ba94c65dd506"
      value_template: >-
        {% if is_state('sensor.mud_room_smoke_detector_smoke', '3') %}
          Testing
        {% elif is_state('sensor.mud_room_smoke_detector_smoke', '2') %}
          Smoke
        {% elif is_state('sensor.mud_room_smoke_detector_carbon_monoxide', '2') %}
          CO
        {% elif is_state('sensor.mud_room_smoke_detector_smoke', '6') or is_state('sensor.mud_room_smoke_detector_carbon_monoxide', '6') %}
          Silenced
        {% elif is_state('sensor.mud_room_smoke_detector_carbon_monoxide', '5') %}
          CO_EOL
        {% else %}
          Clear
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.mud_room_smoke_detector_smoke', '3') %}
          mdi:cloud-alert
        {% elif is_state('sensor.mud_room_smoke_detector_smoke', '2') %}
          mdi:fire
        {% elif is_state('sensor.mud_room_smoke_detector_carbon_monoxide', '2') %}
          mdi:cloud-alert
        {% elif is_state('sensor.mud_room_smoke_detector_smoke', '6') or is_state('sensor.mud_room_smoke_detector_carbon_monoxide', '6') %}
          mdi:volume-mute
        {% elif is_state('sensor.mud_room_smoke_detector_carbon_monoxide', '5') %}
          mdi:cloud-alert
        {% else %}
          mdi:smoke-detector
        {% endif %}
- platform: template
  sensors:
    mud_room_fire_alarm_health:
      friendly_name: "Mud Room Fire Alarm Health"
      unique_id: "046fd5c4-aee3-4cfc-95ee-0f92b6fd8d94"
      value_template: >-
        {% if is_state('sensor.mud_room_smoke_detector_system', '5') %}
          Healthy
        {% elif is_state('sensor.mud_room_smoke_detector_system', '1') %}
          Malfunction Detected
        {% elif is_state('sensor.mud_room_smoke_detector_system', '0')  %}
          Malfunction Clear
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.mud_room_smoke_detector_system', '5') %}
          mdi:check-decagram
        {% elif is_state('sensor.mud_room_smoke_detector_system', '1') %}
          mdi:alert
        {% elif is_state('sensor.mud_room_smoke_detector_system', '0')  %}
          mdi:alert-circle-check
        {% else %}
          mdi:help-rhombus
        {% endif %}
