- platform: template
  sensors:
    workshop_fire_alarm_status:
      friendly_name: "Workshop Fire Alarm Status"
      unique_id: "14178c7c-4478-4b62-b67c-ea9aa5467baf"
      value_template: >-
        {% if is_state('sensor.workshop_smoke_detector_smoke', '3') %}
          Testing
        {% elif is_state('sensor.workshop_smoke_detector_smoke', '2') %}
          Smoke
        {% elif is_state('sensor.workshop_smoke_detector_carbon_monoxide', '2') %}
          CO
        {% elif is_state('sensor.workshop_smoke_detector_smoke', '6') or is_state('sensor.workshop_smoke_detector_carbon_monoxide', '6') %}
          Silenced
        {% elif is_state('sensor.workshop_smoke_detector_carbon_monoxide', '5') %}
          CO_EOL
        {% else %}
          Clear
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.workshop_smoke_detector_smoke', '3') %}
          mdi:cloud-alert
        {% elif is_state('sensor.workshop_smoke_detector_smoke', '2') %}
          mdi:fire
        {% elif is_state('sensor.workshop_smoke_detector_carbon_monoxide', '2') %}
          mdi:cloud-alert
        {% elif is_state('sensor.workshop_smoke_detector_smoke', '6') or is_state('sensor.workshop_smoke_detector_carbon_monoxide', '6') %}
          mdi:volume-mute
        {% elif is_state('sensor.workshop_smoke_detector_carbon_monoxide', '5') %}
          mdi:cloud-alert
        {% else %}
          mdi:smoke-detector
        {% endif %}
- platform: template
  sensors:
    workshop_fire_alarm_health:
      friendly_name: "Workshop Fire Alarm Health"
      unique_id: "3e915df9-73ab-4883-ab0e-e8df1433ba06"
      value_template: >-
        {% if is_state('sensor.workshop_smoke_detector_system', '5') %}
          Healthy
        {% elif is_state('sensor.workshop_smoke_detector_system', '1') %}
          Malfunction Detected
        {% elif is_state('sensor.workshop_smoke_detector_system', '0')  %}
          Malfunction Clear
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.workshop_smoke_detector_system', '5') %}
          mdi:check-decagram
        {% elif is_state('sensor.workshop_smoke_detector_system', '1') %}
          mdi:alert
        {% elif is_state('sensor.workshop_smoke_detector_system', '0')  %}
          mdi:alert-circle-check
        {% else %}
          mdi:help-rhombus
        {% endif %}
