- alias: "Alert - Exterior Door"
  id: "alert_exterior_doors"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.front_door
      - binary_sensor.entryway_door
  action:
    service: notify.aprils_devices
    data_template:
      title: "🚪 {{ trigger.to_state.name }}"
      data:
        push:
          sound: "shake.caf"
      message: >-
        {% if trigger.to_state.state == 'on' %}
          Someone opened the {{ trigger.to_state.name }}
        {% else %}
          Someone closed the {{ trigger.to_state.name }}
        {% endif %}
