- alias: "Alert - Exterior Door"
  id: "alert_exterior_doors"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.back_door
      - binary_sensor.bedroom_door
      - binary_sensor.entryway_door
      - binary_sensor.forbidden_door
      - binary_sensor.front_door
      - binary_sensor.left_shed_door
      - binary_sensor.right_shed_door
  action:
    service: notify.aprils_devices
    data_template:
      title: "🚪 {{ trigger.to_state.name }}"
      data:
        push:
          sound: "shake.caf"
      message: >-
        {% if trigger.to_state.state == 'on' %}
          The {{ trigger.to_state.name }} is now open
        {% else %}
          The {{ trigger.to_state.name }} is now closed
        {% endif %}

- alias: "Alert - Doors Locked / Unlocked"
  id: "alert_doors_locked_unlocked"
  trigger:
    platform: state
    entity_id:
      - lock.back_door
      - lock.front_door
  action:
    service: notify.aprils_devices
    data_template:
      title: "🔐 {{ trigger.to_state.name }}"
      data:
        push:
          sound: "shake.caf"
      message: >-
        {% if trigger.to_state.state == 'locked' %}
          🔒 {{ trigger.to_state.name }} has been locked 👍🏻
        {% else %}
          🔓 {{ trigger.to_state.name }} has been unlocked! 🚨
        {% endif %}
