- alias: "Alert - Flamethrower State"
  id: "alert_flamethrower_state"
  trigger:
    platform: state
    entity_id:
      - "switch.office_fireplace"
      - "switch.family_room_flamethrower"
  action:
    service: notify.aprils_devices
    data_template:
      title: "🪵 {{ trigger.to_state.name }}"
      data:
        push:
          sound: "shake.caf"
      message: >-
        {% if trigger.to_state.state == 'on' %}
          🔥 Flamethrower On 🔥
        {% else %}
          💦 Flamethrower Off 😌
        {% endif %}
