- alias: "Alert - UPS Changed State"
  id: "alert_ups_changed_state"
  trigger:
    platform: state
    entity_id:
      - "sensor.belgian_hare_ups_status"
      - "sensor.network_ups_status"
      - "sensor.office_ups_status"
      - "sensor.workbench_ups_status"
  action:
    service: notify.aprils_devices
    data:
      title: "🔋 {{ trigger.to_state.name }}"
      message: "New State: {{ trigger.to_state.state }}"
      data:
        push:
          sound: "shake.caf"
