# Stuff needed for Wifi to work!

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${ip}
    gateway: 10.9.1.1
    subnet: 255.255.255.0
    dns1: 10.3.2.3
    dns2: 10.9.1.1

mdns:
  disabled: false

sensor:
  - platform: wifi_signal
    name: "${human_devicename} WiFi Signal"
    update_interval: 60s
    id: wifi_signal_db
    icon: mdi:wifi
    entity_category: diagnostic

  # Reports the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: "${human_devicename} WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic
    device_class: ""

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${human_devicename} IP Address"
    ssid:
      name: "${human_devicename} Connected SSID"
    bssid:
      name: "${human_devicename} Connected BSSID"
    mac_address:
      name: "${human_devicename} MAC Address"
    # This is really verbose and likely to bloat the history
    #scan_results:
    #  name: "${human_devicename} Latest Scan Results"
    dns_address:
      name: "${human_devicename} DNS Address"
