# Stuff needed for Wifi to work!

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${ip}
    gateway: 10.9.1.1
    subnet: 255.255.255.0
    dns1: 10.9.1.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename}"
    password: !secret esphome_recovery_wifi_password

# Enable the captive portal if needed
captive_portal:

mdns:
  disabled: false

sensor:
  - platform: wifi_signal
    name: "${human_devicename} WiFi Signal"
    update_interval: 60s
    icon: mdi:wifi

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${human_devicename} IP Address"
    ssid:
      name: "${human_devicename} Connected SSID"
    bssid:
      name: "${human_devicename} Connected BSSID"
    mac_address:
      name: "${human_devicename} MAC Address"
    # This is really verbose and likely to bloat the history
    #scan_results:
    #  name: "${human_devicename} Latest Scan Results"
    dns_address:
      name: "${human_devicename} DNS Address"
