- platform: generic_thermostat
  name: "Office Heat"
  unique_id: "064bf14a-8a30-4d82-987b-0a2a7659c2d4"
  heater: switch.office_fireplace
  target_sensor: sensor.office_temperature
  min_temp: 50
  max_temp: 90
  ac_mode: false
  target_temp: 68
  cold_tolerance: 1.5
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 60
  keep_alive:
    minutes: 3
  initial_hvac_mode: "off"
  away_temp: 50
  precision: 0.5
