

#
# Give access to the cameras on the 3D printers
#
- platform: mjpeg
  name: sable_camera
  still_image_url: https://sable.opsnlops.io/webcam/?action=snapshot
  mjpeg_url: https://sable.opsnlops.io/webcam/?action=stream
- platform: mjpeg
  name: mable_camera
  still_image_url: https://mable.opsnlops.io/webcam/?action=snapshot
  mjpeg_url: https://mable.opsnlops.io/webcam/?action=stream
