# Convert whole-home power (W) into cumulative energy (kWh) for the Energy dashboard.
- platform: integration
  source: sensor.aprils_nest_energy_monitor_electric_consumption_w
  name: "Home Energy Consumption"
  unit_prefix: k
  unit_time: h
  round: 3

# Convert hot water heater power (W) into cumulative energy (kWh).
- platform: integration
  source: sensor.hot_water_heater_electric_consumption_w
  name: "Hot Water Heater Energy"
  unit_prefix: k
  unit_time: h
  round: 3

# Convert main network wrack PDU power (W) into cumulative energy (kWh).
- platform: integration
  source: sensor.main_rack_pdu_ac_power_consumption
  name: "Main Network Wrack Energy"
  unit_prefix: k
  unit_time: h
  round: 3

# Convert EV charger power (W) into cumulative energy (kWh).
- platform: integration
  source: sensor.sparky_power
  name: "Sparky Energy"
  unit_prefix: k
  unit_time: h
  round: 3

# Integrate the cost rate (USD/h) to total cost (USD).
- platform: integration
  source: sensor.electricity_cost_rate
  name: "Electricity Cost"
  unit_time: h
  round: 2
