
#
# This has been taken from the moonraker docs!
#  https://github.com/Arksine/moonraker/blob/master/docs/example-home-assistant.yaml
#
#  Credit to GitHub users @Kruppes and @pedrolamas
#

- platform: rest
  name: sable_sensor
  resource: "https://sable.opsnlops.io/printer/objects/query?heater_bed&extruder&print_stats&toolhead&display_status&virtual_sdcard"
  json_attributes_path: "$.result.status"
  json_attributes:
    - heater_bed
    - extruder
    - print_stats
    - toolhead
    - display_status
    - virtual_sdcard
  value_template: >-
    {{ 'OK' if ('result' in value_json) else None }}

