#######
#
# Inovelli Switch LED Notifications
#
#  See https://nathanfiscus.github.io/inovelli-notification-calc/
#

# Make the light on the switch next to the half bathroom red
# if there's someone in the bathroom
# Half Bathroom
- alias: "Notification - Half Bath Occupied"
  trigger:
    platform: state
    entity_id: "binary_sensor.half_bathroom_motion"
    to: "on"
  action:
    service: zwave_js.bulk_set_partial_config_parameters
    target:
      entity_id: switch.family_room_ceiling_fan
    data:
      parameter: 8
      value: 72353534
- alias: "Notification - Half Bath Empty"
  trigger:
    platform: state
    entity_id: "binary_sensor.half_bathroom_motion"
    to: "off"
    for: "00:00:15"
  action:
    service: zwave_js.bulk_set_partial_config_parameters
    target:
      entity_id: switch.family_room_ceiling_fan
    data:
      parameter: 8
      value: 67326

# Send a notifcation when the front door unlocks
- alias: "Notification - Front Door Unlocked"
  trigger:
    platform: state
    entity_id:
      - "lock.front_door"
      - "lock.back_door"
    to: "unlocked"
  action:
    - service: zwave.set_config_parameter
      data:
        node_id: 18
        parameter: 8
        value: 68094506
    - service: zwave.set_config_parameter
      data:
        node_id: 20
        parameter: 16
        value: 34474539
    - service: zwave.set_config_parameter
      data:
        node_id: 21
        parameter: 16
        value: 34474539
    - service: zwave.set_config_parameter
      data:
        node_id: 22
        parameter: 16
        value: 34474539
    - service: zwave.set_config_parameter
      data:
        node_id: 24
        parameter: 16
        value: 34474539
    - service: zwave.set_config_parameter
      data:
        node_id: 28
        parameter: 24
        value: 68094507
    - service: zwave.set_config_parameter
      data:
        node_id: 29
        parameter: 8
        value: 68094506
    - service: zwave.set_config_parameter
      data:
        node_id: 30
        parameter: 8
        value: 68094506

# Scene controllers
- alias: "Set Kitchen Cleanup"
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.kitchen_scene_controller
      scene_id: 1
  action:
    service: homeassistant.turn_on
    entity_id: scene.kitchen_cleanup
- alias: "Set Normal Evening"
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.kitchen_scene_controller
      scene_id: 2
  action:
    service: homeassistant.turn_on
    entity_id: scene.normal_evening
