# Dim the lights at 9pm if I'm home
- alias: "Dim lights at 9:00pm"
  initial_state: true
  trigger:
    platform: time
    at: "21:00:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
      - condition: state
        entity_id: person.april
        state: home
  action:
    - service: script.turn_on
      entity_id: script.low_key_scene
