- alias: "Run At Sunset 20 minutes before the actual sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:20:00"
  action:
    service: homeassistant.turn_on
    entity_id: scene.at_sunset

# Turn off the outside lights at sunrise
- alias: "Turn off the outside lights at sunrise"
  trigger:
    platform: sun
    event: sunrise
    offset: "00:20:00"
  action:
    service: homeassistant.turn_on
    entity_id: scene.at_sunrise


# Dim the outside lights around bedtime
- alias: "Dim the outside lights at sleep time"
  trigger:
    platform: time
    at: "22:30:00"
  action:
    service: homeassistant.turn_on
    entity_id: scene.sleepy_time