#
#  A simple telegram bot!
#

- alias: "Bot - Weather"
  id: "bot_weather_comamnd"
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: "/weather"
  action:
    - service: telegram_bot.send_message
      data:
        target: "{{ trigger.event.data.chat_id }}"
        title: "🌡 South Whidbey Weather"
        message: >-
          It's {{ states('sensor.outside_temperature') }}{{ state_attr('sensor.outside_temperature', 'unit_of_measurement') }} outside
