substitutions:
  devicename: bedroom-window-shade
  human_devicename: Bedroom Window Shade
  ip: 10.9.1.216

  # Things for roller blinds
  my_stepper: my_stepper
  speed: 600 steps/s
  report_in: "0"
  endstop: "10000"

  # These are the pins next to the v5 / GND pins. Yes, they're in this order.
  pina: GPIO13
  pinb: GPIO12
  pinc: GPIO14
  pind: GPIO27

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  esp32: !include common/device-classes/esp32.yaml


<<: !include common/roller_shade.yaml