substitutions:
  devicename: bedroom_fan
  human_devicename: Bedroom Fan
  ip: 10.9.1.214
  icon: "mdi:fan"

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  sonoff_s31: !include common/device-classes/sonoff_s31.yaml
