substitutions:
  devicename: bedroom_fairy_lights
  human_devicename: Bedroom Fairy Lights
  ip: 10.9.1.222
  icon: "mdi:string-lights"

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  sonoff_s31: !include common/device-classes/athom_smart_plug.yaml
