substitutions:
  devicename: bedroom-window-shade
  human_devicename: Bedroom Window Shade
  ip: 10.9.1.216

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  esp32: !include common/device-classes/esp32.yaml

esphome:
  includes:
    - "custom_components/lc709203f/lc709203f.h"

i2c:

sensor:
  - platform: lc709203f
    address: "0x0B"
    battery_voltage:
      name: "${human_devicename} Battery Voltage"
    battery_level:
      name: "${human_devicename} Battery Level"
    cell_charge:
      name: "${human_devicename} Cell Charge"
    update_interval: 20s

binary_sensor:
  - platform: gpio
    pin:
      number: 23
      inverted: true
    name: "${human_devicename} Low Battery"
    icon: "mdi:battery-20"
    filters:
      - delayed_off: 5s
      - delayed_on: 5s
