substitutions:
  devicename: bunnys_room_bed_fan
  human_devicename: Bunny's Room Bed Fan
  ip: 10.9.1.226
  icon: "mdi:fan"

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  sonoff_s31: !include common/device-classes/athom_smart_plug.yaml
