substitutions:
  devicename: co2-monitor
  human_devicename: CO2 Monitor
  ip: 10.9.1.240

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  rp2040: !include common/device-classes/rp2040.yaml

logger:

# Use i2c0 on the rp2040 so we don't stomp on UART0
i2c:
  sda: 20
  scl: 21
  scan: true


sensor:
  - platform: scd4x
    address: 0x62
    co2:
      name: "${human_devicename} CO2"
    temperature:
      name: "${human_devicename} Temperature"
    humidity:
      name: "${human_devicename} Humidity"
    update_interval: 15s
