substitutions:
  devicename: family_room_floor_fan
  human_devicename: Family Room Floor Fan
  ip: 10.9.1.213
  icon: "mdi:fan"

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  sonoff_s31: !include common/device-classes/sonoff_s31.yaml
