substitutions:
  devicename: family_room_tv_power
  human_devicename: Family Room TV Power
  ip: 10.9.1.208
  icon: mdi:television-shimmer

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  sonoff_s31: !include common/device-classes/sonoff_s31.yaml
  