substitutions:
  devicename: family-room-temperature
  human_devicename: Family Room Temperature
  ip: 10.9.1.202

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  esp32: !include common/device-classes/esp32.yaml

i2c:

sensor:
  - platform: bme280
    temperature:
      name: "Family Room Temperature"
      oversampling: 16x
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
      icon: mdi:thermometer-lines
    pressure:
      name: "Family Room Pressure"
      oversampling: 16x
      icon: mdi:chart-line-variant
    humidity:
      name: "Family Room Humidity"
      oversampling: 16x
      icon: mdi:water-percent
    address: 0x77
    update_interval: 20s
