substitutions:
  devicename: family-room-thermostat
  human_devicename: Family Room Thermostat
  ip: 10.9.1.224

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  esp32: !include common/device-classes/esp32.yaml

display:
  - platform: lcd_gpio
    dimensions: 16x2
    data_pins:
      - 5
      - 18
      - 19
      - 33
    enable_pin: 25
    rs_pin: 26
    lambda: |-
      // Print the current state of things
      it.printf("%.1fF %s\n%.1fF %.1fF %.0f%%", id(family_room_temperature).state, id(heater_state).state.c_str(), 
                id(current_set_point).state, id(outside_temperature).state, id(family_room_humidity).state);

i2c:

sensor:
  - platform: bme280_i2c
    temperature:
      name: "Family Room Temperature"
      id: family_room_temperature
      oversampling: 16x
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
      icon: mdi:thermometer-lines
    pressure:
      name: "Family Room Pressure"
      id: family_room_pressure
      oversampling: 16x
      icon: mdi:chart-line-variant
    humidity:
      name: "Family Room Humidity"
      id: family_room_humidity
      oversampling: 16x
      icon: mdi:water-percent
    address: 0x77
    update_interval: 20s

  # Import some data from Home Assistant
  - platform: homeassistant
    name: "Current Set Point"
    id: current_set_point
    entity_id: climate.family_room_heat
    attribute: temperature
    internal: true
  - platform: homeassistant
    id: outside_temperature
    name: "Outside Temperature"
    entity_id: sensor.outside_temperature
    internal: true

text_sensor:
  - platform: homeassistant
    name: "Heater State"
    id: heater_state
    entity_id: climate.family_room_heat
    attribute: hvac_action
    internal: true