substitutions:
  devicename: family-room-fireplace
  human_devicename: Family Room Fireplace
  ip: 10.9.1.212
  icon: mdi:fireplace

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  shelly1: !include common/device-classes/shelly1.yaml
