substitutions:
  devicename: family-room-temperature-v2
  human_devicename: Family Room Temperature V2
  ip: 10.9.1.224

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  esp32: !include common/device-classes/esp32.yaml

display:
  - platform: lcd_gpio
    dimensions: 16x2
    data_pins:
      - 5
      - 18
      - 19
      - 33
    enable_pin: 25
    rs_pin: 26
    lambda: |-
      // Print the current time
      it.strftime("%I:%M:%S %p\n%m/%d/%Y", id(sntp_time).now());


i2c:

sensor:
  - platform: bme280
    temperature:
      name: "Family Room Temperature V2"
      oversampling: 16x
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
      icon: mdi:thermometer-lines
    pressure:
      name: "Family Room Pressure V2"
      oversampling: 16x
      icon: mdi:chart-line-variant
    humidity:
      name: "Family Room Humidity V2"
      oversampling: 16x
      icon: mdi:water-percent
    address: 0x77
    update_interval: 20s
