substitutions:
  devicename: gray_fan
  human_devicename: Gray Fan
  ip: 10.9.1.239
  icon: "mdi:fan"

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  sonoff_s31: !include common/device-classes/athom_smart_plug_v2.yaml
