substitutions:
  devicename: ir-monitor
  human_devicename: IR Monitor
  ip: 10.9.1.233

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  esp32: !include common/device-classes/esp32.yaml


remote_receiver:
  id: rcvr
  pin:
    number: GPIO26
    inverted: true
    mode:
      input: true
      pullup: true
  # high 55% tolerance is recommended for some remote control units
  tolerance: 55%  
  dump: all

remote_transmitter:
  pin: GPIO25
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

climate:
  - platform: climate_ir_lg
    name: "Test AC"
    receiver_id: rcvr