substitutions:
  devicename: laundry_room_window_fan
  human_devicename: Laundry Room Window Fan
  ip: 10.9.1.202
  icon: "mdi:fan"

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  sonoff_s31: !include common/device-classes/athom_smart_plug.yaml

