substitutions:
  devicename: mable_printer
  human_devicename: Mable Printer
  ip: 10.9.1.222
  icon: "mdi:printer-3d"

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  sonoff_s31: !include common/device-classes/athom_smart_plug.yaml
