substitutions:
  devicename: office-presence
  human_devicename: Office Presence
  ip: 10.9.1.237

packages:
  base: !include common/base.yaml
  ethernet: !include common/olimex-ethernet.yaml
  esp32: !include common/device-classes/esp32.yaml
  mmwave: !include common/leapmmw_sensor.yaml

