substitutions:
  devicename: office_window_fan
  human_devicename: Office Window Fan
  ip: 10.9.1.220
  icon: mdi:fan

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  sonoff_s31: !include common/device-classes/sonoff_s31.yaml
