substitutions:
  devicename: office-fireplace
  human_devicename: Office Fireplace
  ip: 10.9.1.211
  icon: mdi:fireplace

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  shelly1: !include common/device-classes/shelly1.yaml
