substitutions:
  devicename: shelly1-test-unit
  human_devicename: Shelly1 Test Unit
  ip: 10.9.1.215
  icon: mdi:test-tube

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  shelly1: !include common/device-classes/shelly1.yaml
