substitutions:
  devicename: zigbee-coordinator-west
  human_devicename: Zigbee Coordinator West

esphome:
  name: ${devicename}
  project:
    name: tubezb.cc2652-poe-2023
    version: "3.0"
  on_boot:
    priority: 600
    then:
      - switch.turn_on: zRST_gpio
      - delay: 15ms
      - switch.turn_off: zRST_gpio

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

packages:
  base: !include common/base.yaml
  mqtt: !include common/mqtt.yaml

external_components:
  - source: github://tube0013/esphome-stream-server-v2
  - source: github://syssi/esphome-zeroconf@main

dashboard_import:
  package_import_url: github://tube0013/tube_gateways/models/current/tubeszb-cc2652-poe-2023/firmware/esphome/tubeszb-cc2652-poe-2023.yaml

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  
  manual_ip:
    static_ip: 10.9.1.76
    gateway: 10.9.1.1
    subnet: 255.255.255.0

# Enable logging
logger:
  level: DEBUG

ota:

# Turn on the web server
web_server:

preferences:
  flash_write_interval: 10min


# Enable Home Assistant API
api:
  reboot_timeout: 0s

script:
  - id: fw_update_mode
    then:
      - switch.turn_on: zBSL
      - delay: 1s
      - switch.turn_on: zRST_gpio
      - delay: 1s
      - switch.turn_off: zRST_gpio
      - logger.log: "Delaying ~10 seconds for cc2652p2 to settle"
      - delay: 11s
      - switch.turn_off: zBSL
      - logger.log: "Please try update with cc-bsl tool now"
      - logger.log: "cc-bsl usage: cc2538-bsl.py -p socket://10.9.1.75:6638 -evw firmware.hex"
      
switch:
  - platform: gpio
    pin: 5
    id: zRST_gpio
    inverted: yes
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 16
    name: "${human_devicename} Zigbee Module Bootloader Pin"
    id: zBSL
    inverted: yes
    restore_mode: ALWAYS_OFF
    disabled_by_default: true

button:
  - platform: template
    name: "${human_devicename} Zigbee Module Reset"
    id: zRST
    on_press:
      - switch.turn_on: zRST_gpio
      - delay: 15ms
      - switch.turn_off: zRST_gpio

  - platform: template
    name: "${human_devicename} Trigger Zigbee Module Bootloader"
    disabled_by_default: true
    on_press:
      - script.execute: fw_update_mode

uart:
  id: uart_bus
  rx_pin: GPIO36
  tx_pin: GPIO4
  baud_rate: 115200

stream_server:
  uart_id: uart_bus
  port: 6638
  id: ss

binary_sensor:
  - platform: stream_server
    stream_server: ss
    name: "${human_devicename} TubesZB Serial Connected"

zeroconf:
  - service: "tubeszb"
    protocol: "tcp"
    port: 6638
    txt:
      version: 1.0
      name: TubesZB
      radio_type: znp
      baud_rate: 115200
      data_flow_control: software

text_sensor:
  - platform: ethernet_info
    ip_address:
      name: "${human_devicename} IP Address"
